apiVersion: apps/v1
kind: Deployment

metadata:
  name: grafana-deploy

spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  
  template:
    metadata:
      name: grafana-deploy
      labels:
        app: grafana
  
    spec:
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      containers:
        - name: grafana
          image: abhi8585/grafana:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/data-grafana"
              name: grafana-storage
      
      restartPolicy: Always