apiVersion: apps/v1
kind: Deployment

metadata:
  name: prometheus-deploy

spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  
  template:
    metadata:
      name: prometheus-deploy
      labels:
        app: prometheus
  
    spec:
      volumes:
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: prometheus-pvc
      containers:
      - name: prometheus
        image: abhi8585/prometheus:v1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: "/data-prometheus"
            name: prometheus-storage